<?php

$_COS_LANG_MODULE['blocks_confirm_deleted'] = 'Blok blev slettet';
$_COS_LANG_MODULE['blocks_confirm_insert'] = 'Blok er tilføjet';
$_COS_LANG_MODULE['blocks_sort_success'] = 'Blokkenes orden er blevet gemt';
$_COS_LANG_MODULE['blocks_label_delete_block'] = 'Slet';
$_COS_LANG_MODULE['blocks_label_edit_block'] = 'Ret blok';
$_COS_LANG_MODULE['blocks_label_add_block'] = 'Tilføj Blok';
$_COS_LANG_MODULE['blocks_form_show_title'] = 'Vis titel';
$_COS_LANG_MODULE['blocks_form_error_title'] = 'Indtast titel';
$_COS_LANG_MODULE['blocks_form_error_content'] = 'Indtast indhold';
