<?php

$_COS_LANG_MODULE['blocks_sort_success'] = 'Blokkenes orden er blevet gemt';
$_COS_LANG_MODULE['Delete block'] = 'Slet blok';
$_COS_LANG_MODULE['Delete'] = 'Slet';
$_COS_LANG_MODULE['Edit block'] = 'Edit blok';
$_COS_LANG_MODULE['Add block'] = 'Tilføj blok';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Content'] = 'Indhold';
$_COS_LANG_MODULE['Display title'] = 'Display title';
$_COS_LANG_MODULE['Submit'] = 'Indsend';
$_COS_LANG_MODULE['Insert a title'] = 'Indsæt en titel';
$_COS_LANG_MODULE['No block content'] = 'Ingen blok indhold';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['blocks_confirm_insert'] = 'Blok er tilføjet';
$_COS_LANG_MODULE['blocks_confirm_deleted'] = 'Blok blev slettet';
