<?php

$_COS_LANG_MODULE['Blocks has been sorted'] = 'Blokke er blevet sorteret';
$_COS_LANG_MODULE['Delete block'] = 'Slet blok';
$_COS_LANG_MODULE['Delete'] = 'Slet';
$_COS_LANG_MODULE['Edit block'] = 'Edit blok';
$_COS_LANG_MODULE['Add block'] = 'Tilføj blok';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Content'] = 'Indhold';
$_COS_LANG_MODULE['Display title'] = 'Display title';
$_COS_LANG_MODULE['Submit'] = 'Indsend';
$_COS_LANG_MODULE['Insert a title'] = 'Indsæt en titel';
$_COS_LANG_MODULE['No block content'] = 'Ingen blok indhold';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Block has been added'] = 'Blok er blevet tilføjet';
$_COS_LANG_MODULE['Block has been deleted'] = 'Blok er slettet';
$_COS_LANG_MODULE['Block has been inserted'] = 'Blok er blevet indsat';
