<?php

$_COS_LANG_MODULE['Blocks has been sorted'] = '块已经整理';
$_COS_LANG_MODULE['Delete block'] = '删除块';
$_COS_LANG_MODULE['Delete'] = '删除';
$_COS_LANG_MODULE['Edit block'] = '编辑块';
$_COS_LANG_MODULE['Add block'] = '添加块';
$_COS_LANG_MODULE['Title'] = '称号';
$_COS_LANG_MODULE['Content'] = '内容';
$_COS_LANG_MODULE['Display title'] = '显示标题';
$_COS_LANG_MODULE['Submit'] = '提交';
$_COS_LANG_MODULE['Insert a title'] = '插入标题';
$_COS_LANG_MODULE['No block content'] = '无块内容';
$_COS_LANG_MODULE['Edit'] = '编辑';
$_COS_LANG_MODULE['Block has been added'] = '块已被添加';
$_COS_LANG_MODULE['Block has been deleted'] = '块已经被删除';
$_COS_LANG_MODULE['Block has been inserted'] = '块已被插入';
