<?php

$_COS_LANG_MODULE['blocks_sort_success'] = '块的订单已保存';
$_COS_LANG_MODULE['Delete block'] = '删除块';
$_COS_LANG_MODULE['Delete'] = '删除';
$_COS_LANG_MODULE['Edit block'] = '编辑块';
$_COS_LANG_MODULE['Add block'] = '添加块';
$_COS_LANG_MODULE['Title'] = '称号';
$_COS_LANG_MODULE['Content'] = '内容';
$_COS_LANG_MODULE['Display title'] = '显示标题';
$_COS_LANG_MODULE['Submit'] = '提交';
$_COS_LANG_MODULE['Insert a title'] = '插入标题';
$_COS_LANG_MODULE['No block content'] = '无块内容';
$_COS_LANG_MODULE['Edit'] = '编辑';
$_COS_LANG_MODULE['blocks_confirm_insert'] = '加座';
$_COS_LANG_MODULE['blocks_confirm_deleted'] = '删除块';
