<?php


// Translation of file /modules/blocks/custom/delete.php

$_COS_LANG_MODULE['blocks_confirm_deleted'] = 'Block deleted';

// Translation of file /modules/blocks/custom/add.php

$_COS_LANG_MODULE['blocks_confirm_insert'] = 'Block added';

// Translation of file /modules/blocks/custom/edit.php


// Translation of file /modules/blocks/module.php

$_COS_LANG_MODULE['blocks_sort_success'] = 'Block order has been saved';
$_COS_LANG_MODULE['blocks_label_delete_block'] = 'Delete block';
$_COS_LANG_MODULE['blocks_label_edit_block'] = 'Edit block';
$_COS_LANG_MODULE['blocks_label_add_block'] = 'Add block';
$_COS_LANG_MODULE['blocks_form_show_title'] = 'Show Title';
$_COS_LANG_MODULE['blocks_form_error_title'] = 'Add title';
$_COS_LANG_MODULE['blocks_form_error_content'] = 'Add content';
