<?php


// Translation of file /modules/blocks/module.php

$_COS_LANG_MODULE['Blocks has been sorted'] = 'Blocks has been sorted';
$_COS_LANG_MODULE['Delete block'] = 'Delete block';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Edit block'] = 'Edit block';
$_COS_LANG_MODULE['Add block'] = 'Add block';
$_COS_LANG_MODULE['Title'] = 'Title';
$_COS_LANG_MODULE['Content'] = 'Content';
$_COS_LANG_MODULE['Display title'] = 'Display title';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Insert a title'] = 'Insert a title';
$_COS_LANG_MODULE['No block content'] = 'No block content';
$_COS_LANG_MODULE['Edit'] = 'Edit';

// Translation of file /modules/blocks/custom/module.php

$_COS_LANG_MODULE['Block has been added'] = 'Block has been added';
$_COS_LANG_MODULE['Block has been deleted'] = 'Block has been deleted';
$_COS_LANG_MODULE['Block has been inserted'] = 'Block has been inserted';
