<?php

$_COS_LANG_MODULE['Blocks has been sorted'] = 'Blokker har blitt sortert';
$_COS_LANG_MODULE['Delete block'] = 'Slett blokk';
$_COS_LANG_MODULE['Delete'] = 'Slett';
$_COS_LANG_MODULE['Edit block'] = 'Edit blokk';
$_COS_LANG_MODULE['Add block'] = 'Legg blokk';
$_COS_LANG_MODULE['Title'] = 'Tittel';
$_COS_LANG_MODULE['Content'] = 'Innhold';
$_COS_LANG_MODULE['Display title'] = 'Skjerm tittel';
$_COS_LANG_MODULE['Submit'] = 'Send inn';
$_COS_LANG_MODULE['Insert a title'] = 'Sett inn en tittel';
$_COS_LANG_MODULE['No block content'] = 'Ingen blokk innhold';
$_COS_LANG_MODULE['Edit'] = 'Redigere';
$_COS_LANG_MODULE['Block has been added'] = 'Block har blitt lagt';
$_COS_LANG_MODULE['Block has been deleted'] = 'Block er slettet';
$_COS_LANG_MODULE['Block has been inserted'] = 'Block er satt inn';
