<?php

$_COS_LANG_MODULE['blocks_sort_success'] = 'Bestill av blokkene har blitt lagret';
$_COS_LANG_MODULE['Delete block'] = 'Slett blokk';
$_COS_LANG_MODULE['Delete'] = 'Slett';
$_COS_LANG_MODULE['Edit block'] = 'Edit blokk';
$_COS_LANG_MODULE['Add block'] = 'Legg blokk';
$_COS_LANG_MODULE['Title'] = 'Tittel';
$_COS_LANG_MODULE['Content'] = 'Innhold';
$_COS_LANG_MODULE['Display title'] = 'Skjerm tittel';
$_COS_LANG_MODULE['Submit'] = 'Send inn';
$_COS_LANG_MODULE['Insert a title'] = 'Sett inn en tittel';
$_COS_LANG_MODULE['No block content'] = 'Ingen blokk innhold';
$_COS_LANG_MODULE['Edit'] = 'Redigere';
$_COS_LANG_MODULE['blocks_confirm_insert'] = 'Block legges';
$_COS_LANG_MODULE['blocks_confirm_deleted'] = 'Block ble slettet';
