<?php

$_COS_LANG_MODULE['blocks_confirm_deleted'] = 'Block ble slettet';
$_COS_LANG_MODULE['blocks_confirm_insert'] = 'Block legges';
$_COS_LANG_MODULE['blocks_sort_success'] = 'Bestill av blokkene har blitt lagret';
$_COS_LANG_MODULE['blocks_label_delete_block'] = 'Slett';
$_COS_LANG_MODULE['blocks_label_edit_block'] = 'Redigere blokk';
$_COS_LANG_MODULE['blocks_label_add_block'] = 'Legg Block';
$_COS_LANG_MODULE['blocks_form_show_title'] = 'Vis tittel';
$_COS_LANG_MODULE['blocks_form_error_title'] = 'Skriv inn tittel';
$_COS_LANG_MODULE['blocks_form_error_content'] = 'Tast innhold';
