<?php

$_MODULE_MENU[] = array(
        'title' => lang::translate('blocks_menu_sort'),
        'url' => '/blocks/sort/index',
        'auth' => 'admin',
);


$_MODULE_MENU[] = array (
        'title' => lang::translate('blocks_costum_block_list'),
        'url' => '/blocks/custom/index',
        'auth' => 'admin',
);

$_MODULE_MENU[] = array(
        'title' => lang::translate('blocks_menu_costum_add'),
        'url' => '/blocks/custom/add',
        'auth' => 'admin',
);
