<?php

$_COS_LANG_MODULE['blocks_sort_success'] = 'Blockauftrag wurde gespeichert';
$_COS_LANG_MODULE['Delete block'] = 'Block löschen';
$_COS_LANG_MODULE['Delete'] = 'Löschen';
$_COS_LANG_MODULE['Edit block'] = 'Block bearbeiten';
$_COS_LANG_MODULE['Add block'] = 'Block hinzufügen';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Content'] = 'Inhalt';
$_COS_LANG_MODULE['Display title'] = 'Titelanzeige';
$_COS_LANG_MODULE['Submit'] = 'Einreichen';
$_COS_LANG_MODULE['Insert a title'] = 'Legen Sie einen Titel';
$_COS_LANG_MODULE['No block content'] = 'Nein Blockgehalt';
$_COS_LANG_MODULE['Edit'] = 'Bearbeiten';
$_COS_LANG_MODULE['blocks_confirm_insert'] = 'Block hinzugefügt';
$_COS_LANG_MODULE['blocks_confirm_deleted'] = 'Block gelöscht';
