<?php

$_COS_LANG_MODULE['blocks_sort_success'] = 'Järjestystä lohkojen on tallennettu';
$_COS_LANG_MODULE['Delete block'] = 'Poista lohko';
$_COS_LANG_MODULE['Delete'] = 'Poistaa';
$_COS_LANG_MODULE['Edit block'] = 'Muokkaa lohko';
$_COS_LANG_MODULE['Add block'] = 'Lisää lohko';
$_COS_LANG_MODULE['Title'] = 'Otsikko';
$_COS_LANG_MODULE['Content'] = 'Pitoisuus';
$_COS_LANG_MODULE['Display title'] = 'Näytön otsikko';
$_COS_LANG_MODULE['Submit'] = 'Esittää';
$_COS_LANG_MODULE['Insert a title'] = 'Aseta otsikko';
$_COS_LANG_MODULE['No block content'] = 'Ei lohko sisältöä';
$_COS_LANG_MODULE['Edit'] = 'Muokata';
$_COS_LANG_MODULE['blocks_confirm_insert'] = 'Block lisätään';
$_COS_LANG_MODULE['blocks_confirm_deleted'] = 'Block on poistettu';
