<?php

$_COS_LANG_MODULE['blocks_confirm_deleted'] = 'Block on poistettu';
$_COS_LANG_MODULE['blocks_confirm_insert'] = 'Block lisätään';
$_COS_LANG_MODULE['blocks_sort_success'] = 'Järjestystä lohkojen on tallennettu';
$_COS_LANG_MODULE['blocks_label_delete_block'] = 'Poistaa';
$_COS_LANG_MODULE['blocks_label_edit_block'] = 'Muokkaa lohko';
$_COS_LANG_MODULE['blocks_label_add_block'] = 'Lisää Block';
$_COS_LANG_MODULE['blocks_form_show_title'] = 'Näytä otsikko';
$_COS_LANG_MODULE['blocks_form_error_title'] = 'Kirjoita otsikko';
$_COS_LANG_MODULE['blocks_form_error_content'] = 'Anna sisällön';
