<?php

$_COS_LANG_MODULE['Blocks has been sorted'] = 'Blocks har sorterats';
$_COS_LANG_MODULE['Delete block'] = 'Radera blocket';
$_COS_LANG_MODULE['Delete'] = 'Radera';
$_COS_LANG_MODULE['Edit block'] = 'Redigera blocket';
$_COS_LANG_MODULE['Add block'] = 'Lägg blocket';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Content'] = 'Innehåll';
$_COS_LANG_MODULE['Display title'] = 'Visnings titel';
$_COS_LANG_MODULE['Submit'] = 'Skicka';
$_COS_LANG_MODULE['Insert a title'] = 'Sätt en titel';
$_COS_LANG_MODULE['No block content'] = 'Ingen blocket innehåll';
$_COS_LANG_MODULE['Edit'] = 'Redigera';
$_COS_LANG_MODULE['Block has been added'] = 'Block har lagts';
$_COS_LANG_MODULE['Block has been deleted'] = 'Blocket har raderats';
$_COS_LANG_MODULE['Block has been inserted'] = 'Block har satts in';
