<?php

$_COS_LANG_MODULE['blocks_confirm_deleted'] = 'Block utgå';
$_COS_LANG_MODULE['blocks_confirm_insert'] = 'Block tillsattes';
$_COS_LANG_MODULE['blocks_sort_success'] = 'Block order har sparats';
$_COS_LANG_MODULE['blocks_label_delete_block'] = 'Radera blocket';
$_COS_LANG_MODULE['blocks_label_edit_block'] = 'Redigera blocket';
$_COS_LANG_MODULE['blocks_label_add_block'] = 'Lägg blocket';
$_COS_LANG_MODULE['blocks_form_show_title'] = 'Visa titel';
$_COS_LANG_MODULE['blocks_form_error_title'] = 'Lägg till rubrik';
$_COS_LANG_MODULE['blocks_form_error_content'] = 'Lägg till innehåll';
