<?php

$_COS_LANG_MODULE['blocks_sort_success'] = 'Block order har sparats';
$_COS_LANG_MODULE['Delete block'] = 'Radera blocket';
$_COS_LANG_MODULE['Delete'] = 'Radera';
$_COS_LANG_MODULE['Edit block'] = 'Redigera blocket';
$_COS_LANG_MODULE['Add block'] = 'Lägg blocket';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Content'] = 'Innehåll';
$_COS_LANG_MODULE['Display title'] = 'Visnings titel';
$_COS_LANG_MODULE['Submit'] = 'Skicka';
$_COS_LANG_MODULE['Insert a title'] = 'Sätt en titel';
$_COS_LANG_MODULE['No block content'] = 'Ingen blocket innehåll';
$_COS_LANG_MODULE['Edit'] = 'Redigera';
$_COS_LANG_MODULE['blocks_confirm_insert'] = 'Block tillsattes';
$_COS_LANG_MODULE['blocks_confirm_deleted'] = 'Block utgå';
